train_database_dir: "../in/train"
valid_database_dir: "../in/valid"
train_dir: "../out"
model: "song"
experiment: "lr=1e-3_bs=200_y-noise=3e-2"
epochs: 80
batch_size_training: 200
batch_size_testing: 50
learning_rate: 0.001
seed: 42
no_mr_params: 5
no_frames: 175
y_noise: !!float 3e-2
y_noise_validation: !!float 3e-2